spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/NeoflexPraktika
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: 2222
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml